FROM almalinux:9
ENV COURSE="devops"\
        TRAINER="siva"
ARG DURATION="120hrs"
RUN echo "Hi course is {{ $COURSE }}, Tranier is {{ $TRAINER }}, duration is {{ $DURATION }}"
CMD ["sleep","1000"]