FROM almalinux:9
ENV COURSE="devops"\
DURATION="120hrs"
        
ARG TRAINER="siva"
RUN echo "Hi course is {{ $COURSE }}, Tranier is {{ $TRAINER }}, duration is {{ $DURATION }}"
CMD ["sleep","1000"]